package ec.com.sisapus.modelo;
// Generated 24/03/2014 10:48:04 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Analisispreciounitario generated by hbm2java
 */
public class Analisispreciounitario  implements java.io.Serializable {


     private Integer codigoApu;
     private Presupuesto presupuesto;
     private Rubro rubro;
     private Double analApuMat;
     private Double analApuEqherr;
     private Double analApuMob;
     private Double analApuTran;
     private Double costDirApu;
     private Double costIndApu;
     private Double costOtrosIndApu;
     private Double costotApu;
     private Double rendApu;
     private Set<ManoobraApu> manoobraApus = new HashSet<ManoobraApu>(0);
     private Set<TransporteApu> transporteApus = new HashSet<TransporteApu>(0);
     private Set<EquipherrApu> equipherrApus = new HashSet<EquipherrApu>(0);
     private Set<MaterialApu> materialApus = new HashSet<MaterialApu>(0);

    public Analisispreciounitario() {
    }

    public Analisispreciounitario(Presupuesto presupuesto, Rubro rubro, Double analApuMat, Double analApuEqherr, Double analApuMob, Double analApuTran, Double costDirApu, Double costIndApu, Double costOtrosIndApu, Double costotApu, Double rendApu, Set<ManoobraApu> manoobraApus, Set<TransporteApu> transporteApus, Set<EquipherrApu> equipherrApus, Set<MaterialApu> materialApus) {
       this.presupuesto = presupuesto;
       this.rubro = rubro;
       this.analApuMat = analApuMat;
       this.analApuEqherr = analApuEqherr;
       this.analApuMob = analApuMob;
       this.analApuTran = analApuTran;
       this.costDirApu = costDirApu;
       this.costIndApu = costIndApu;
       this.costOtrosIndApu = costOtrosIndApu;
       this.costotApu = costotApu;
       this.rendApu = rendApu;
       this.manoobraApus = manoobraApus;
       this.transporteApus = transporteApus;
       this.equipherrApus = equipherrApus;
       this.materialApus = materialApus;
    }
   
    public Integer getCodigoApu() {
        return this.codigoApu;
    }
    
    public void setCodigoApu(Integer codigoApu) {
        this.codigoApu = codigoApu;
    }
    public Presupuesto getPresupuesto() {
        return this.presupuesto;
    }
    
    public void setPresupuesto(Presupuesto presupuesto) {
        this.presupuesto = presupuesto;
    }
    public Rubro getRubro() {
        return this.rubro;
    }
    
    public void setRubro(Rubro rubro) {
        this.rubro = rubro;
    }
    public Double getAnalApuMat() {
        return this.analApuMat;
    }
    
    public void setAnalApuMat(Double analApuMat) {
        this.analApuMat = analApuMat;
    }
    public Double getAnalApuEqherr() {
        return this.analApuEqherr;
    }
    
    public void setAnalApuEqherr(Double analApuEqherr) {
        this.analApuEqherr = analApuEqherr;
    }
    public Double getAnalApuMob() {
        return this.analApuMob;
    }
    
    public void setAnalApuMob(Double analApuMob) {
        this.analApuMob = analApuMob;
    }
    public Double getAnalApuTran() {
        return this.analApuTran;
    }
    
    public void setAnalApuTran(Double analApuTran) {
        this.analApuTran = analApuTran;
    }
    public Double getCostDirApu() {
        return this.costDirApu;
    }
    
    public void setCostDirApu(Double costDirApu) {
        this.costDirApu = costDirApu;
    }
    public Double getCostIndApu() {
        return this.costIndApu;
    }
    
    public void setCostIndApu(Double costIndApu) {
        this.costIndApu = costIndApu;
    }
    public Double getCostOtrosIndApu() {
        return this.costOtrosIndApu;
    }
    
    public void setCostOtrosIndApu(Double costOtrosIndApu) {
        this.costOtrosIndApu = costOtrosIndApu;
    }
    public Double getCostotApu() {
        return this.costotApu;
    }
    
    public void setCostotApu(Double costotApu) {
        this.costotApu = costotApu;
    }
    public Double getRendApu() {
        return this.rendApu;
    }
    
    public void setRendApu(Double rendApu) {
        this.rendApu = rendApu;
    }
    public Set<ManoobraApu> getManoobraApus() {
        return this.manoobraApus;
    }
    
    public void setManoobraApus(Set<ManoobraApu> manoobraApus) {
        this.manoobraApus = manoobraApus;
    }
    public Set<TransporteApu> getTransporteApus() {
        return this.transporteApus;
    }
    
    public void setTransporteApus(Set<TransporteApu> transporteApus) {
        this.transporteApus = transporteApus;
    }
    public Set<EquipherrApu> getEquipherrApus() {
        return this.equipherrApus;
    }
    
    public void setEquipherrApus(Set<EquipherrApu> equipherrApus) {
        this.equipherrApus = equipherrApus;
    }
    public Set<MaterialApu> getMaterialApus() {
        return this.materialApus;
    }
    
    public void setMaterialApus(Set<MaterialApu> materialApus) {
        this.materialApus = materialApus;
    }




}


