package ec.com.sisapus.modelo;
// Generated 18/12/2014 06:11:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Categoriapreciounitario generated by hbm2java
 */
public class Categoriapreciounitario  implements java.io.Serializable {


     private Integer codigoCatApu;
     private String descripcionCatApu;
     private Set analisispreciounitarios = new HashSet(0);

    public Categoriapreciounitario() {
        this.codigoCatApu = 0;
    }

    public Categoriapreciounitario(String descripcionCatApu, Set analisispreciounitarios) {
       this.descripcionCatApu = descripcionCatApu;
       this.analisispreciounitarios = analisispreciounitarios;
    }
   
    public Integer getCodigoCatApu() {
        return this.codigoCatApu;
    }
    
    public void setCodigoCatApu(Integer codigoCatApu) {
        this.codigoCatApu = codigoCatApu;
    }
    public String getDescripcionCatApu() {
        return this.descripcionCatApu;
    }
    
    public void setDescripcionCatApu(String descripcionCatApu) {
        this.descripcionCatApu = descripcionCatApu;
    }
    public Set getAnalisispreciounitarios() {
        return this.analisispreciounitarios;
    }
    
    public void setAnalisispreciounitarios(Set analisispreciounitarios) {
        this.analisispreciounitarios = analisispreciounitarios;
    }




}


