package ec.com.sisapus.modelo;
// Generated 06/01/2015 02:51:14 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Categoriaequipoherramienta generated by hbm2java
 */
public class Categoriaequipoherramienta  implements java.io.Serializable {


     private Integer codCatEqherr;
     private String nombCatEqherr;
     private Set equipoherramientas = new HashSet(0);

    public Categoriaequipoherramienta() {
        this.codCatEqherr = 0;
    }

    public Categoriaequipoherramienta(String nombCatEqherr, Set equipoherramientas) {
       this.nombCatEqherr = nombCatEqherr;
       this.equipoherramientas = equipoherramientas;
    }
   
    public Integer getCodCatEqherr() {
        return this.codCatEqherr;
    }
    
    public void setCodCatEqherr(Integer codCatEqherr) {
        this.codCatEqherr = codCatEqherr;
    }
    public String getNombCatEqherr() {
        return this.nombCatEqherr;
    }
    
    public void setNombCatEqherr(String nombCatEqherr) {
        this.nombCatEqherr = nombCatEqherr;
    }
    public Set getEquipoherramientas() {
        return this.equipoherramientas;
    }
    
    public void setEquipoherramientas(Set equipoherramientas) {
        this.equipoherramientas = equipoherramientas;
    }




}


