package ec.com.sisapus.modelo;
// Generated 24/03/2014 10:48:04 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Categoriaequipoherramienta generated by hbm2java
 */
public class Categoriaequipoherramienta  implements java.io.Serializable {


     private Integer codCatEqherr;
     private String nombCatEqherr;
     private Set<Equipoherramienta> equipoherramientas = new HashSet<Equipoherramienta>(0);

    public Categoriaequipoherramienta() {
        this.codCatEqherr = 0;
    }

    public Categoriaequipoherramienta(String nombCatEqherr, Set<Equipoherramienta> equipoherramientas) {
       this.nombCatEqherr = nombCatEqherr;
       this.equipoherramientas = equipoherramientas;
    }
   
    public Integer getCodCatEqherr() {
        return this.codCatEqherr;
    }
    
    public void setCodCatEqherr(Integer codCatEqherr) {
        this.codCatEqherr = codCatEqherr;
    }
    public String getNombCatEqherr() {
        return this.nombCatEqherr;
    }
    
    public void setNombCatEqherr(String nombCatEqherr) {
        this.nombCatEqherr = nombCatEqherr;
    }
    public Set<Equipoherramienta> getEquipoherramientas() {
        return this.equipoherramientas;
    }
    
    public void setEquipoherramientas(Set<Equipoherramienta> equipoherramientas) {
        this.equipoherramientas = equipoherramientas;
    }




}


