package ec.com.sisapus.modelo;
// Generated 06/01/2015 11:20:58 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Categoriarubro generated by hbm2java
 */
public class Categoriarubro  implements java.io.Serializable {


     private Integer codigoCatRubro;
     private String descripcionCatRubro;
     private Set rubros = new HashSet(0);

    public Categoriarubro() {
        
         this.codigoCatRubro = 0;
    }

    public Categoriarubro(String descripcionCatRubro, Set rubros) {
       this.descripcionCatRubro = descripcionCatRubro;
       this.rubros = rubros;
    }
   
    public Integer getCodigoCatRubro() {
        return this.codigoCatRubro;
    }
    
    public void setCodigoCatRubro(Integer codigoCatRubro) {
        this.codigoCatRubro = codigoCatRubro;
    }
    public String getDescripcionCatRubro() {
        return this.descripcionCatRubro;
    }
    
    public void setDescripcionCatRubro(String descripcionCatRubro) {
        this.descripcionCatRubro = descripcionCatRubro;
    }
    public Set getRubros() {
        return this.rubros;
    }
    
    public void setRubros(Set rubros) {
        this.rubros = rubros;
    }




}


