package ec.com.sisapus.modelo;
// Generated 18/12/2014 06:11:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Cronograma generated by hbm2java
 */
public class Cronograma  implements java.io.Serializable {


     private Integer codigoCron;
     private Detallecronograma detallecronograma;
     private Proyecto proyecto;
     private Integer periodoCron;
     private Date fechiniCron;
     private Date fechfinCron;

    public Cronograma() {
        this.codigoCron = 0;
        this.detallecronograma = new Detallecronograma();
    }

    public Cronograma(Detallecronograma detallecronograma, Proyecto proyecto, Integer periodoCron, Date fechiniCron, Date fechfinCron) {
       this.detallecronograma = detallecronograma;
       this.proyecto = proyecto;
       this.periodoCron = periodoCron;
       this.fechiniCron = fechiniCron;
       this.fechfinCron = fechfinCron;
    }
   
    public Integer getCodigoCron() {
        return this.codigoCron;
    }
    
    public void setCodigoCron(Integer codigoCron) {
        this.codigoCron = codigoCron;
    }
    public Detallecronograma getDetallecronograma() {
        return this.detallecronograma;
    }
    
    public void setDetallecronograma(Detallecronograma detallecronograma) {
        this.detallecronograma = detallecronograma;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public Integer getPeriodoCron() {
        return this.periodoCron;
    }
    
    public void setPeriodoCron(Integer periodoCron) {
        this.periodoCron = periodoCron;
    }
    public Date getFechiniCron() {
        return this.fechiniCron;
    }
    
    public void setFechiniCron(Date fechiniCron) {
        this.fechiniCron = fechiniCron;
    }
    public Date getFechfinCron() {
        return this.fechfinCron;
    }
    
    public void setFechfinCron(Date fechfinCron) {
        this.fechfinCron = fechfinCron;
    }




}


