package ec.com.sisapus.modelo;
// Generated 24/03/2014 10:48:04 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cronograma generated by hbm2java
 */
public class Cronograma  implements java.io.Serializable {


     private Integer codigoCron;
     private Proyecto proyecto;
     private String tiempodurCron;
     private Integer periodoCron;
     private Date fechiniCron;
     private Date fechfinCron;
     private Set<Cronogramatrabajo> cronogramatrabajos = new HashSet<Cronogramatrabajo>(0);

    public Cronograma() {
    }

    public Cronograma(Proyecto proyecto, String tiempodurCron, Integer periodoCron, Date fechiniCron, Date fechfinCron, Set<Cronogramatrabajo> cronogramatrabajos) {
       this.proyecto = proyecto;
       this.tiempodurCron = tiempodurCron;
       this.periodoCron = periodoCron;
       this.fechiniCron = fechiniCron;
       this.fechfinCron = fechfinCron;
       this.cronogramatrabajos = cronogramatrabajos;
    }
   
    public Integer getCodigoCron() {
        return this.codigoCron;
    }
    
    public void setCodigoCron(Integer codigoCron) {
        this.codigoCron = codigoCron;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public String getTiempodurCron() {
        return this.tiempodurCron;
    }
    
    public void setTiempodurCron(String tiempodurCron) {
        this.tiempodurCron = tiempodurCron;
    }
    public Integer getPeriodoCron() {
        return this.periodoCron;
    }
    
    public void setPeriodoCron(Integer periodoCron) {
        this.periodoCron = periodoCron;
    }
    public Date getFechiniCron() {
        return this.fechiniCron;
    }
    
    public void setFechiniCron(Date fechiniCron) {
        this.fechiniCron = fechiniCron;
    }
    public Date getFechfinCron() {
        return this.fechfinCron;
    }
    
    public void setFechfinCron(Date fechfinCron) {
        this.fechfinCron = fechfinCron;
    }
    public Set<Cronogramatrabajo> getCronogramatrabajos() {
        return this.cronogramatrabajos;
    }
    
    public void setCronogramatrabajos(Set<Cronogramatrabajo> cronogramatrabajos) {
        this.cronogramatrabajos = cronogramatrabajos;
    }




}


