package ec.com.sisapus.modelo;
// Generated 24/03/2014 10:48:04 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Cronogramatrabajo generated by hbm2java
 */
public class Cronogramatrabajo  implements java.io.Serializable {


     private Integer codCrotra;
     private Cronograma cronograma;
     private Presupuesto presupuesto;
     private Date fechiniCrontr;
     private Date fechfinCrontr;
     private Double porcentCrontr;
     private Double valorCrontr;

    public Cronogramatrabajo() {
    }

    public Cronogramatrabajo(Cronograma cronograma, Presupuesto presupuesto, Date fechiniCrontr, Date fechfinCrontr, Double porcentCrontr, Double valorCrontr) {
       this.cronograma = cronograma;
       this.presupuesto = presupuesto;
       this.fechiniCrontr = fechiniCrontr;
       this.fechfinCrontr = fechfinCrontr;
       this.porcentCrontr = porcentCrontr;
       this.valorCrontr = valorCrontr;
    }
   
    public Integer getCodCrotra() {
        return this.codCrotra;
    }
    
    public void setCodCrotra(Integer codCrotra) {
        this.codCrotra = codCrotra;
    }
    public Cronograma getCronograma() {
        return this.cronograma;
    }
    
    public void setCronograma(Cronograma cronograma) {
        this.cronograma = cronograma;
    }
    public Presupuesto getPresupuesto() {
        return this.presupuesto;
    }
    
    public void setPresupuesto(Presupuesto presupuesto) {
        this.presupuesto = presupuesto;
    }
    public Date getFechiniCrontr() {
        return this.fechiniCrontr;
    }
    
    public void setFechiniCrontr(Date fechiniCrontr) {
        this.fechiniCrontr = fechiniCrontr;
    }
    public Date getFechfinCrontr() {
        return this.fechfinCrontr;
    }
    
    public void setFechfinCrontr(Date fechfinCrontr) {
        this.fechfinCrontr = fechfinCrontr;
    }
    public Double getPorcentCrontr() {
        return this.porcentCrontr;
    }
    
    public void setPorcentCrontr(Double porcentCrontr) {
        this.porcentCrontr = porcentCrontr;
    }
    public Double getValorCrontr() {
        return this.valorCrontr;
    }
    
    public void setValorCrontr(Double valorCrontr) {
        this.valorCrontr = valorCrontr;
    }




}


