package ec.com.sisapus.modelo;
// Generated 06/01/2015 02:17:13 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cronograma generated by hbm2java
 */
public class Cronograma  implements java.io.Serializable {


     private Integer codigoCron;
     private Proyecto proyecto;
     private Integer periodoCron;
     private Date fechiniCron;
     private Date fechfinCron;
     private Set detallecronogramas = new HashSet(0);

    public Cronograma() {
 this.codigoCron = 0;
        this.proyecto = new Proyecto();
    }

    public Cronograma(Proyecto proyecto, Integer periodoCron, Date fechiniCron, Date fechfinCron, Set detallecronogramas) {
       this.proyecto = proyecto;
       this.periodoCron = periodoCron;
       this.fechiniCron = fechiniCron;
       this.fechfinCron = fechfinCron;
       this.detallecronogramas = detallecronogramas;
    }
   
    public Integer getCodigoCron() {
        return this.codigoCron;
    }
    
    public void setCodigoCron(Integer codigoCron) {
        this.codigoCron = codigoCron;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public Integer getPeriodoCron() {
        return this.periodoCron;
    }
    
    public void setPeriodoCron(Integer periodoCron) {
        this.periodoCron = periodoCron;
    }
    public Date getFechiniCron() {
        return this.fechiniCron;
    }
    
    public void setFechiniCron(Date fechiniCron) {
        this.fechiniCron = fechiniCron;
    }
    public Date getFechfinCron() {
        return this.fechfinCron;
    }
    
    public void setFechfinCron(Date fechfinCron) {
        this.fechfinCron = fechfinCron;
    }
    public Set getDetallecronogramas() {
        return this.detallecronogramas;
    }
    
    public void setDetallecronogramas(Set detallecronogramas) {
        this.detallecronogramas = detallecronogramas;
    }




}


