package ec.com.sisapus.modelo;
// Generated 24/03/2014 10:48:04 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ejecutado generated by hbm2java
 */
public class Ejecutado  implements java.io.Serializable {


     private Integer codigoEjec;
     private Proyecto proyecto;
     private String duracionEjec;
     private Integer periodoEjec;
     private Date fechainicioEjec;
     private Date fechafinEjec;
     private Set<Ejecutadopresup> ejecutadopresups = new HashSet<Ejecutadopresup>(0);

    public Ejecutado() {
    }

    public Ejecutado(Proyecto proyecto, String duracionEjec, Integer periodoEjec, Date fechainicioEjec, Date fechafinEjec, Set<Ejecutadopresup> ejecutadopresups) {
       this.proyecto = proyecto;
       this.duracionEjec = duracionEjec;
       this.periodoEjec = periodoEjec;
       this.fechainicioEjec = fechainicioEjec;
       this.fechafinEjec = fechafinEjec;
       this.ejecutadopresups = ejecutadopresups;
    }
   
    public Integer getCodigoEjec() {
        return this.codigoEjec;
    }
    
    public void setCodigoEjec(Integer codigoEjec) {
        this.codigoEjec = codigoEjec;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public String getDuracionEjec() {
        return this.duracionEjec;
    }
    
    public void setDuracionEjec(String duracionEjec) {
        this.duracionEjec = duracionEjec;
    }
    public Integer getPeriodoEjec() {
        return this.periodoEjec;
    }
    
    public void setPeriodoEjec(Integer periodoEjec) {
        this.periodoEjec = periodoEjec;
    }
    public Date getFechainicioEjec() {
        return this.fechainicioEjec;
    }
    
    public void setFechainicioEjec(Date fechainicioEjec) {
        this.fechainicioEjec = fechainicioEjec;
    }
    public Date getFechafinEjec() {
        return this.fechafinEjec;
    }
    
    public void setFechafinEjec(Date fechafinEjec) {
        this.fechafinEjec = fechafinEjec;
    }
    public Set<Ejecutadopresup> getEjecutadopresups() {
        return this.ejecutadopresups;
    }
    
    public void setEjecutadopresups(Set<Ejecutadopresup> ejecutadopresups) {
        this.ejecutadopresups = ejecutadopresups;
    }




}


