package ec.com.sisapus.modelo;
// Generated 24/03/2014 10:48:04 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Ejecutadopresup generated by hbm2java
 */
public class Ejecutadopresup  implements java.io.Serializable {


     private Integer codEjpr;
     private Ejecutado ejecutado;
     private Presupuestado presupuestado;
     private Double porcentaje;
     private Double valorreal;
     private Date fechainicioEjec;
     private Date fechafinEjec;

    public Ejecutadopresup() {
    }

    public Ejecutadopresup(Ejecutado ejecutado, Presupuestado presupuestado, Double porcentaje, Double valorreal, Date fechainicioEjec, Date fechafinEjec) {
       this.ejecutado = ejecutado;
       this.presupuestado = presupuestado;
       this.porcentaje = porcentaje;
       this.valorreal = valorreal;
       this.fechainicioEjec = fechainicioEjec;
       this.fechafinEjec = fechafinEjec;
    }
   
    public Integer getCodEjpr() {
        return this.codEjpr;
    }
    
    public void setCodEjpr(Integer codEjpr) {
        this.codEjpr = codEjpr;
    }
    public Ejecutado getEjecutado() {
        return this.ejecutado;
    }
    
    public void setEjecutado(Ejecutado ejecutado) {
        this.ejecutado = ejecutado;
    }
    public Presupuestado getPresupuestado() {
        return this.presupuestado;
    }
    
    public void setPresupuestado(Presupuestado presupuestado) {
        this.presupuestado = presupuestado;
    }
    public Double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(Double porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Double getValorreal() {
        return this.valorreal;
    }
    
    public void setValorreal(Double valorreal) {
        this.valorreal = valorreal;
    }
    public Date getFechainicioEjec() {
        return this.fechainicioEjec;
    }
    
    public void setFechainicioEjec(Date fechainicioEjec) {
        this.fechainicioEjec = fechainicioEjec;
    }
    public Date getFechafinEjec() {
        return this.fechafinEjec;
    }
    
    public void setFechafinEjec(Date fechafinEjec) {
        this.fechafinEjec = fechafinEjec;
    }




}


