package ec.com.sisapus.modelo;
// Generated 07/01/2015 01:13:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Equipoherramienta generated by hbm2java
 */
public class Equipoherramienta  implements java.io.Serializable {


     private Integer codigoEqherr;
     private Categoriaequipoherramienta categoriaequipoherramienta;
     private String nombreEqherr;
     private Double costohoraEqherr;
     private Set equipherrApus = new HashSet(0);

    public Equipoherramienta() {
          this.codigoEqherr=0;
        this.categoriaequipoherramienta = new Categoriaequipoherramienta();
    }

    public Equipoherramienta(Categoriaequipoherramienta categoriaequipoherramienta, String nombreEqherr, Double costohoraEqherr, Set equipherrApus) {
       this.categoriaequipoherramienta = categoriaequipoherramienta;
       this.nombreEqherr = nombreEqherr;
       this.costohoraEqherr = costohoraEqherr;
       this.equipherrApus = equipherrApus;
    }
   
    public Integer getCodigoEqherr() {
        return this.codigoEqherr;
    }
    
    public void setCodigoEqherr(Integer codigoEqherr) {
        this.codigoEqherr = codigoEqherr;
    }
    public Categoriaequipoherramienta getCategoriaequipoherramienta() {
        return this.categoriaequipoherramienta;
    }
    
    public void setCategoriaequipoherramienta(Categoriaequipoherramienta categoriaequipoherramienta) {
        this.categoriaequipoherramienta = categoriaequipoherramienta;
    }
    public String getNombreEqherr() {
        return this.nombreEqherr;
    }
    
    public void setNombreEqherr(String nombreEqherr) {
        this.nombreEqherr = nombreEqherr;
    }
    public Double getCostohoraEqherr() {
        return this.costohoraEqherr;
    }
    
    public void setCostohoraEqherr(Double costohoraEqherr) {
        this.costohoraEqherr = costohoraEqherr;
    }
    public Set getEquipherrApus() {
        return this.equipherrApus;
    }
    
    public void setEquipherrApus(Set equipherrApus) {
        this.equipherrApus = equipherrApus;
    }




}


