package ec.com.sisapus.modelo;
// Generated 06/01/2015 02:51:14 PM by Hibernate Tools 3.2.1.GA



/**
 * EquipherrApu generated by hbm2java
 */
public class EquipherrApu  implements java.io.Serializable {


     private Integer codEqherrApu;
     private Analisispreciounitario analisispreciounitario;
     private Equipoherramienta equipoherramienta;
     private String descEqherrApu;
     private Integer cantEqherrApu;
     private Double tarifaEqherrApu;
     private Double costohoraEqherrApu;
     private Double rendimEqherrApu;
     private Double costotEqherrApu;

    public EquipherrApu() {
        this.codEqherrApu=0;
        this.equipoherramienta = new Equipoherramienta();
        this.analisispreciounitario=new Analisispreciounitario();
    }

    public EquipherrApu(Analisispreciounitario analisispreciounitario, Equipoherramienta equipoherramienta, String descEqherrApu, Integer cantEqherrApu, Double tarifaEqherrApu, Double costohoraEqherrApu, Double rendimEqherrApu, Double costotEqherrApu) {
       this.analisispreciounitario = analisispreciounitario;
       this.equipoherramienta = equipoherramienta;
       this.descEqherrApu = descEqherrApu;
       this.cantEqherrApu = cantEqherrApu;
       this.tarifaEqherrApu = tarifaEqherrApu;
       this.costohoraEqherrApu = costohoraEqherrApu;
       this.rendimEqherrApu = rendimEqherrApu;
       this.costotEqherrApu = costotEqherrApu;
    }
   
    public Integer getCodEqherrApu() {
        return this.codEqherrApu;
    }
    
    public void setCodEqherrApu(Integer codEqherrApu) {
        this.codEqherrApu = codEqherrApu;
    }
    public Analisispreciounitario getAnalisispreciounitario() {
        return this.analisispreciounitario;
    }
    
    public void setAnalisispreciounitario(Analisispreciounitario analisispreciounitario) {
        this.analisispreciounitario = analisispreciounitario;
    }
    public Equipoherramienta getEquipoherramienta() {
        return this.equipoherramienta;
    }
    
    public void setEquipoherramienta(Equipoherramienta equipoherramienta) {
        this.equipoherramienta = equipoherramienta;
    }
    public String getDescEqherrApu() {
        return this.descEqherrApu;
    }
    
    public void setDescEqherrApu(String descEqherrApu) {
        this.descEqherrApu = descEqherrApu;
    }
    public Integer getCantEqherrApu() {
        return this.cantEqherrApu;
    }
    
    public void setCantEqherrApu(Integer cantEqherrApu) {
        this.cantEqherrApu = cantEqherrApu;
    }
    public Double getTarifaEqherrApu() {
        return this.tarifaEqherrApu;
    }
    
    public void setTarifaEqherrApu(Double tarifaEqherrApu) {
        this.tarifaEqherrApu = tarifaEqherrApu;
    }
    public Double getCostohoraEqherrApu() {
        return this.costohoraEqherrApu;
    }
    
    public void setCostohoraEqherrApu(Double costohoraEqherrApu) {
        this.costohoraEqherrApu = costohoraEqherrApu;
    }
    public Double getRendimEqherrApu() {
        return this.rendimEqherrApu;
    }
    
    public void setRendimEqherrApu(Double rendimEqherrApu) {
        this.rendimEqherrApu = rendimEqherrApu;
    }
    public Double getCostotEqherrApu() {
        return this.costotEqherrApu;
    }
    
    public void setCostotEqherrApu(Double costotEqherrApu) {
        this.costotEqherrApu = costotEqherrApu;
    }




}


