package ec.com.sisapus.modelo;
// Generated 06/01/2015 02:17:13 PM by Hibernate Tools 3.2.1.GA



/**
 * ManoobraApu generated by hbm2java
 */
public class ManoobraApu  implements java.io.Serializable {


     private Integer codMoApu;
     private Manoobra manoobra;
     private String descMoApu;
     private String categMoApu;
     private Integer cantMoApu;
     private Double costojrhMoApu;
     private Double costohoraMoApu;
     private Double rendimMoApu;
     private Double costotMoApu;

    public ManoobraApu() {
        this.codMoApu=0;
        this.manoobra = new Manoobra();
    }

    public ManoobraApu(Manoobra manoobra, String descMoApu, String categMoApu, Integer cantMoApu, Double costojrhMoApu, Double costohoraMoApu, Double rendimMoApu, Double costotMoApu) {
       this.manoobra = manoobra;
       this.descMoApu = descMoApu;
       this.categMoApu = categMoApu;
       this.cantMoApu = cantMoApu;
       this.costojrhMoApu = costojrhMoApu;
       this.costohoraMoApu = costohoraMoApu;
       this.rendimMoApu = rendimMoApu;
       this.costotMoApu = costotMoApu;
    }
   
    public Integer getCodMoApu() {
        return this.codMoApu;
    }
    
    public void setCodMoApu(Integer codMoApu) {
        this.codMoApu = codMoApu;
    }
    public Manoobra getManoobra() {
        return this.manoobra;
    }
    
    public void setManoobra(Manoobra manoobra) {
        this.manoobra = manoobra;
    }
    public String getDescMoApu() {
        return this.descMoApu;
    }
    
    public void setDescMoApu(String descMoApu) {
        this.descMoApu = descMoApu;
    }
    public String getCategMoApu() {
        return this.categMoApu;
    }
    
    public void setCategMoApu(String categMoApu) {
        this.categMoApu = categMoApu;
    }
    public Integer getCantMoApu() {
        return this.cantMoApu;
    }
    
    public void setCantMoApu(Integer cantMoApu) {
        this.cantMoApu = cantMoApu;
    }
    public Double getCostojrhMoApu() {
        return this.costojrhMoApu;
    }
    
    public void setCostojrhMoApu(Double costojrhMoApu) {
        this.costojrhMoApu = costojrhMoApu;
    }
    public Double getCostohoraMoApu() {
        return this.costohoraMoApu;
    }
    
    public void setCostohoraMoApu(Double costohoraMoApu) {
        this.costohoraMoApu = costohoraMoApu;
    }
    public Double getRendimMoApu() {
        return this.rendimMoApu;
    }
    
    public void setRendimMoApu(Double rendimMoApu) {
        this.rendimMoApu = rendimMoApu;
    }
    public Double getCostotMoApu() {
        return this.costotMoApu;
    }
    
    public void setCostotMoApu(Double costotMoApu) {
        this.costotMoApu = costotMoApu;
    }




}


