package ec.com.sisapus.modelo;
// Generated 24/03/2014 10:48:04 AM by Hibernate Tools 3.2.1.GA



/**
 * MaterialApu generated by hbm2java
 */
public class MaterialApu  implements java.io.Serializable {


     private Integer codMatApu;
     private Analisispreciounitario analisispreciounitario;
     private Material material;
     private String descMatApu;
     private String unidMatApu;
     private Integer cantMatApu;
     private Double preunitMatApu;
     private Double costotMatApu;

    public MaterialApu() {
    }

    public MaterialApu(Analisispreciounitario analisispreciounitario, Material material, String descMatApu, String unidMatApu, Integer cantMatApu, Double preunitMatApu, Double costotMatApu) {
       this.analisispreciounitario = analisispreciounitario;
       this.material = material;
       this.descMatApu = descMatApu;
       this.unidMatApu = unidMatApu;
       this.cantMatApu = cantMatApu;
       this.preunitMatApu = preunitMatApu;
       this.costotMatApu = costotMatApu;
    }
   
    public Integer getCodMatApu() {
        return this.codMatApu;
    }
    
    public void setCodMatApu(Integer codMatApu) {
        this.codMatApu = codMatApu;
    }
    public Analisispreciounitario getAnalisispreciounitario() {
        return this.analisispreciounitario;
    }
    
    public void setAnalisispreciounitario(Analisispreciounitario analisispreciounitario) {
        this.analisispreciounitario = analisispreciounitario;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public String getDescMatApu() {
        return this.descMatApu;
    }
    
    public void setDescMatApu(String descMatApu) {
        this.descMatApu = descMatApu;
    }
    public String getUnidMatApu() {
        return this.unidMatApu;
    }
    
    public void setUnidMatApu(String unidMatApu) {
        this.unidMatApu = unidMatApu;
    }
    public Integer getCantMatApu() {
        return this.cantMatApu;
    }
    
    public void setCantMatApu(Integer cantMatApu) {
        this.cantMatApu = cantMatApu;
    }
    public Double getPreunitMatApu() {
        return this.preunitMatApu;
    }
    
    public void setPreunitMatApu(Double preunitMatApu) {
        this.preunitMatApu = preunitMatApu;
    }
    public Double getCostotMatApu() {
        return this.costotMatApu;
    }
    
    public void setCostotMatApu(Double costotMatApu) {
        this.costotMatApu = costotMatApu;
    }




}


