package ec.com.sisapus.modelo;
// Generated 07/01/2015 01:13:46 PM by Hibernate Tools 3.2.1.GA



/**
 * Presupuesto generated by hbm2java
 */
public class Presupuesto  implements java.io.Serializable {


     private Integer codigoPres;
     private Analisispreciounitario analisispreciounitario;
     private Proyecto proyecto;
     private Rubro rubro;
     private String descripPres;
     private String unidadPres;
     private Integer cantidadPres;
     private Double punitPres;
     private Double ptotPres;
     private Double subtPres;
     private Double ivaPres;
     private Double gastotPres;

    public Presupuesto() {
    }

    public Presupuesto(Analisispreciounitario analisispreciounitario, Proyecto proyecto, Rubro rubro, String descripPres, String unidadPres, Integer cantidadPres, Double punitPres, Double ptotPres, Double subtPres, Double ivaPres, Double gastotPres) {
       this.analisispreciounitario = analisispreciounitario;
       this.proyecto = proyecto;
       this.rubro = rubro;
       this.descripPres = descripPres;
       this.unidadPres = unidadPres;
       this.cantidadPres = cantidadPres;
       this.punitPres = punitPres;
       this.ptotPres = ptotPres;
       this.subtPres = subtPres;
       this.ivaPres = ivaPres;
       this.gastotPres = gastotPres;
    }
   
    public Integer getCodigoPres() {
        return this.codigoPres;
    }
    
    public void setCodigoPres(Integer codigoPres) {
        this.codigoPres = codigoPres;
    }
    public Analisispreciounitario getAnalisispreciounitario() {
        return this.analisispreciounitario;
    }
    
    public void setAnalisispreciounitario(Analisispreciounitario analisispreciounitario) {
        this.analisispreciounitario = analisispreciounitario;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public Rubro getRubro() {
        return this.rubro;
    }
    
    public void setRubro(Rubro rubro) {
        this.rubro = rubro;
    }
    public String getDescripPres() {
        return this.descripPres;
    }
    
    public void setDescripPres(String descripPres) {
        this.descripPres = descripPres;
    }
    public String getUnidadPres() {
        return this.unidadPres;
    }
    
    public void setUnidadPres(String unidadPres) {
        this.unidadPres = unidadPres;
    }
    public Integer getCantidadPres() {
        return this.cantidadPres;
    }
    
    public void setCantidadPres(Integer cantidadPres) {
        this.cantidadPres = cantidadPres;
    }
    public Double getPunitPres() {
        return this.punitPres;
    }
    
    public void setPunitPres(Double punitPres) {
        this.punitPres = punitPres;
    }
    public Double getPtotPres() {
        return this.ptotPres;
    }
    
    public void setPtotPres(Double ptotPres) {
        this.ptotPres = ptotPres;
    }
    public Double getSubtPres() {
        return this.subtPres;
    }
    
    public void setSubtPres(Double subtPres) {
        this.subtPres = subtPres;
    }
    public Double getIvaPres() {
        return this.ivaPres;
    }
    
    public void setIvaPres(Double ivaPres) {
        this.ivaPres = ivaPres;
    }
    public Double getGastotPres() {
        return this.gastotPres;
    }
    
    public void setGastotPres(Double gastotPres) {
        this.gastotPres = gastotPres;
    }




}


