package ec.com.sisapus.modelo;
// Generated 24/03/2014 10:48:04 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Presupuestado generated by hbm2java
 */
public class Presupuestado  implements java.io.Serializable {


     private Integer codPresu;
     private String descripPresu;
     private String detallePresu;
     private String unidadPresu;
     private Integer cantidadPresu;
     private Double valunitarioPresu;
     private Double valtotPresu;
     private Set<Ejecutadopresup> ejecutadopresups = new HashSet<Ejecutadopresup>(0);

    public Presupuestado() {
    }

    public Presupuestado(String descripPresu, String detallePresu, String unidadPresu, Integer cantidadPresu, Double valunitarioPresu, Double valtotPresu, Set<Ejecutadopresup> ejecutadopresups) {
       this.descripPresu = descripPresu;
       this.detallePresu = detallePresu;
       this.unidadPresu = unidadPresu;
       this.cantidadPresu = cantidadPresu;
       this.valunitarioPresu = valunitarioPresu;
       this.valtotPresu = valtotPresu;
       this.ejecutadopresups = ejecutadopresups;
    }
   
    public Integer getCodPresu() {
        return this.codPresu;
    }
    
    public void setCodPresu(Integer codPresu) {
        this.codPresu = codPresu;
    }
    public String getDescripPresu() {
        return this.descripPresu;
    }
    
    public void setDescripPresu(String descripPresu) {
        this.descripPresu = descripPresu;
    }
    public String getDetallePresu() {
        return this.detallePresu;
    }
    
    public void setDetallePresu(String detallePresu) {
        this.detallePresu = detallePresu;
    }
    public String getUnidadPresu() {
        return this.unidadPresu;
    }
    
    public void setUnidadPresu(String unidadPresu) {
        this.unidadPresu = unidadPresu;
    }
    public Integer getCantidadPresu() {
        return this.cantidadPresu;
    }
    
    public void setCantidadPresu(Integer cantidadPresu) {
        this.cantidadPresu = cantidadPresu;
    }
    public Double getValunitarioPresu() {
        return this.valunitarioPresu;
    }
    
    public void setValunitarioPresu(Double valunitarioPresu) {
        this.valunitarioPresu = valunitarioPresu;
    }
    public Double getValtotPresu() {
        return this.valtotPresu;
    }
    
    public void setValtotPresu(Double valtotPresu) {
        this.valtotPresu = valtotPresu;
    }
    public Set<Ejecutadopresup> getEjecutadopresups() {
        return this.ejecutadopresups;
    }
    
    public void setEjecutadopresups(Set<Ejecutadopresup> ejecutadopresups) {
        this.ejecutadopresups = ejecutadopresups;
    }




}


