package ec.com.sisapus.modelo;
// Generated 24/03/2014 10:48:04 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer codigoProy;
     private Usuario usuario;
     private String propiepProy;
     private String contratProy;
     private String obraProy;
     private String ubicProy;
     private Date fechaProy;
     private Double costotProy;
     private Set<Cronograma> cronogramas = new HashSet<Cronograma>(0);
     private Set<Ejecutado> ejecutados = new HashSet<Ejecutado>(0);
     private Set<Presupuesto> presupuestos = new HashSet<Presupuesto>(0);

    public Proyecto() {
        this.codigoProy = 0;
        this.usuario = new Usuario();
    }

    public Proyecto(Usuario usuario, String propiepProy, String contratProy, String obraProy, String ubicProy, Date fechaProy, Double costotProy, Set<Cronograma> cronogramas, Set<Ejecutado> ejecutados, Set<Presupuesto> presupuestos) {
       this.usuario = usuario;
       this.propiepProy = propiepProy;
       this.contratProy = contratProy;
       this.obraProy = obraProy;
       this.ubicProy = ubicProy;
       this.fechaProy = fechaProy;
       this.costotProy = costotProy;
       this.cronogramas = cronogramas;
       this.ejecutados = ejecutados;
       this.presupuestos = presupuestos;
    }
   
    public Integer getCodigoProy() {
        return this.codigoProy;
    }
    
    public void setCodigoProy(Integer codigoProy) {
        this.codigoProy = codigoProy;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getPropiepProy() {
        return this.propiepProy;
    }
    
    public void setPropiepProy(String propiepProy) {
        this.propiepProy = propiepProy;
    }
    public String getContratProy() {
        return this.contratProy;
    }
    
    public void setContratProy(String contratProy) {
        this.contratProy = contratProy;
    }
    public String getObraProy() {
        return this.obraProy;
    }
    
    public void setObraProy(String obraProy) {
        this.obraProy = obraProy;
    }
    public String getUbicProy() {
        return this.ubicProy;
    }
    
    public void setUbicProy(String ubicProy) {
        this.ubicProy = ubicProy;
    }
    public Date getFechaProy() {
        return this.fechaProy;
    }
    
    public void setFechaProy(Date fechaProy) {
        this.fechaProy = fechaProy;
    }
    public Double getCostotProy() {
        return this.costotProy;
    }
    
    public void setCostotProy(Double costotProy) {
        this.costotProy = costotProy;
    }
    public Set<Cronograma> getCronogramas() {
        return this.cronogramas;
    }
    
    public void setCronogramas(Set<Cronograma> cronogramas) {
        this.cronogramas = cronogramas;
    }
    public Set<Ejecutado> getEjecutados() {
        return this.ejecutados;
    }
    
    public void setEjecutados(Set<Ejecutado> ejecutados) {
        this.ejecutados = ejecutados;
    }
    public Set<Presupuesto> getPresupuestos() {
        return this.presupuestos;
    }
    
    public void setPresupuestos(Set<Presupuesto> presupuestos) {
        this.presupuestos = presupuestos;
    }




}


