package ec.com.sisapus.modelo;
// Generated 24/03/2014 10:48:04 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rubro generated by hbm2java
 */
public class Rubro  implements java.io.Serializable {


     private Integer codigoRubro;
     private String nombreRubro;
     private String detalleRubro;
     private String unidadRubro;
     private Set<Presupuesto> presupuestos = new HashSet<Presupuesto>(0);
     private Set<Analisispreciounitario> analisispreciounitarios = new HashSet<Analisispreciounitario>(0);

    public Rubro() {
        this.codigoRubro = 0;
    }

    public Rubro(String nombreRubro, String detalleRubro, String unidadRubro, Set<Presupuesto> presupuestos, Set<Analisispreciounitario> analisispreciounitarios) {
       this.nombreRubro = nombreRubro;
       this.detalleRubro = detalleRubro;
       this.unidadRubro = unidadRubro;
       this.presupuestos = presupuestos;
       this.analisispreciounitarios = analisispreciounitarios;
    }
   
    public Integer getCodigoRubro() {
        return this.codigoRubro;
    }
    
    public void setCodigoRubro(Integer codigoRubro) {
        this.codigoRubro = codigoRubro;
    }
    public String getNombreRubro() {
        return this.nombreRubro;
    }
    
    public void setNombreRubro(String nombreRubro) {
        this.nombreRubro = nombreRubro;
    }
    public String getDetalleRubro() {
        return this.detalleRubro;
    }
    
    public void setDetalleRubro(String detalleRubro) {
        this.detalleRubro = detalleRubro;
    }
    public String getUnidadRubro() {
        return this.unidadRubro;
    }
    
    public void setUnidadRubro(String unidadRubro) {
        this.unidadRubro = unidadRubro;
    }
    public Set<Presupuesto> getPresupuestos() {
        return this.presupuestos;
    }
    
    public void setPresupuestos(Set<Presupuesto> presupuestos) {
        this.presupuestos = presupuestos;
    }
    public Set<Analisispreciounitario> getAnalisispreciounitarios() {
        return this.analisispreciounitarios;
    }
    
    public void setAnalisispreciounitarios(Set<Analisispreciounitario> analisispreciounitarios) {
        this.analisispreciounitarios = analisispreciounitarios;
    }




}


