package ec.com.sisapus.modelo;
// Generated 06/01/2015 02:17:13 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rubro generated by hbm2java
 */
public class Rubro  implements java.io.Serializable {


     private Integer codigoRubro;
     private Categoriarubro categoriarubro;
     private String nombreRubro;
     private String detalleRubro;
     private String unidadRubro;
     private Set presupuestos = new HashSet(0);
     private Set analisispreciounitarios = new HashSet(0);

    public Rubro() {
    }

    public Rubro(Categoriarubro categoriarubro, String nombreRubro, String detalleRubro, String unidadRubro, Set presupuestos, Set analisispreciounitarios) {
       this.categoriarubro = categoriarubro;
       this.nombreRubro = nombreRubro;
       this.detalleRubro = detalleRubro;
       this.unidadRubro = unidadRubro;
       this.presupuestos = presupuestos;
       this.analisispreciounitarios = analisispreciounitarios;
    }
   
    public Integer getCodigoRubro() {
        return this.codigoRubro;
    }
    
    public void setCodigoRubro(Integer codigoRubro) {
        this.codigoRubro = codigoRubro;
    }
    public Categoriarubro getCategoriarubro() {
        return this.categoriarubro;
    }
    
    public void setCategoriarubro(Categoriarubro categoriarubro) {
        this.categoriarubro = categoriarubro;
    }
    public String getNombreRubro() {
        return this.nombreRubro;
    }
    
    public void setNombreRubro(String nombreRubro) {
        this.nombreRubro = nombreRubro;
    }
    public String getDetalleRubro() {
        return this.detalleRubro;
    }
    
    public void setDetalleRubro(String detalleRubro) {
        this.detalleRubro = detalleRubro;
    }
    public String getUnidadRubro() {
        return this.unidadRubro;
    }
    
    public void setUnidadRubro(String unidadRubro) {
        this.unidadRubro = unidadRubro;
    }
    public Set getPresupuestos() {
        return this.presupuestos;
    }
    
    public void setPresupuestos(Set presupuestos) {
        this.presupuestos = presupuestos;
    }
    public Set getAnalisispreciounitarios() {
        return this.analisispreciounitarios;
    }
    
    public void setAnalisispreciounitarios(Set analisispreciounitarios) {
        this.analisispreciounitarios = analisispreciounitarios;
    }




}


